## Pandas and SQL - Continued

In [1]:
#Import pandas
import pandas as pd

### Reading in the NRI point  data
Below, we read the csv files into a Pandas dataFrame as we have in the past - with a few exceptions.

Pandas, like MS Access, will infer the data type from the values it's importing. However, we have some numeric fields that need to be imported as strings: the `recordid`, `fips`, `hydro`, `mhydro`, and `mlra` fields. To do this, we create a dictionary of field names and the field types we want to override. Any fields left of this list will get the default data types.

We will also set the recordid as the index for the dataFrame.

In [2]:
#Create the dataType dictionary
dtypeDict = {'recordid':'str',
             'fips':'str',
             'hydro':'str',
             'mhydro':'str',
             'mlra':'str'
            }

#Read in the data
dfPoint = pd.read_csv('nc_point.csv',
                      index_col='recordid',
                      dtype=dtypeDict)

In [3]:
#Show the data types
dfPoint.dtypes

nriptr        int64
stratum       int64
cluster       int64
xfact         int64
fips         object
hydro        object
mhydro       object
mlra         object
bailey       object
split       float64
impute        int64
impute87      int64
wifact        int64
wcfact        int64
urfact        int64
ukfact      float64
usleflag      int64
s5id         object
s5name       object
surftxt      object
txtmod       object
loslope       int64
hislope       int64
flood        object
ophase       object
tfact         int64
dtype: object

In [4]:
#Have a quick look 
dfPoint.head()

,nriptr,stratum,cluster,xfact,fips,hydro,mhydro,mlra,bailey,split,...,usleflag,s5id,s5name,surftxt,txtmod,loslope,hislope,flood,ophase,tfact
recordid,,,,,,,,,,,,,,,,,,,,,
37001010001,249587,37001,1,1,37001,03030002,0303,136,231A,NaN,...,0,NC0032,APPLING,SL,NON,2,6,NONE,ERODED,4
37001010002,288554,37001,1,17,37001,03030002,0303,136,231A,NaN,...,0,VA0046,ORANGE,SIL,NON,6,10,NONE,0,3
37001010003,274351,37001,1,17,37001,03030002,0303,136,231A,NaN,...,0,SC0017,HERNDON,SIL,NON,15,25,NONE,0,5
37001010004,274167,37001,1,17,37001,03030002,0303,136,231A,NaN,...,0,SC0014,GEORGEVILLE,SIL,NON,10,15,NONE,0,4
37001010005,288554,37001,1,1,37001,03030002,0303,136,231A,NaN,...,0,VA0046,ORANGE,SIL,NON,6,10,NONE,0,3

Ok. Now it's your turn. Import the **nc_trend.csv** file. Set the following columns to be strings: `recordid`,`yr`,`landuse`,`broad`. (Others columns with nominal data should be strings, but this will suffice...). Also, as above, set the `recordid` column to be the index.

In [5]:
dtypeDict = {'recordid':'str',
             'yr':'str',
             'landuse':'str',
             'broad':'str'
            }

dfTrend = pd.read_csv('nc_trend.csv',
                      index_col='recordid',
                      dtype=dtypeDict)
dfTrend.dtypes

yr          object
landuse     object
broad       object
prime        int64
crp          int64
crpcov       int64
crpnum       int64
dblcrop      int64
irtyp        int64
irsor        int64
irsys        int64
ucfact     float64
upfact     float64
lenslop      int64
slope      float64
landcl      object
knoll        int64
wrotat       int64
usle       float64
ei         float64
eiwater    float64
eiwind     float64
aaweq      float64
dtype: object

OK, now we are ready to analyse the data (and learn how Pandas does it...)

* First another example of an aggregate function: Lets count the number of samples and total area of each location within each county using the `dfPoint` dataFrame.

In [6]:
#Create the grouping object
grpCounty = dfPoint.groupby('fips')
type(grpCounty)

pandas.core.groupby.groupby.DataFrameGroupBy

In [7]:
#With this DataFrameGroupBy object we can apply different aggregate functions.
dfX = grpCounty['fips'].agg('count')
dfX.head()

fips
37001    369
37003    191
37005    314
37007    336
37009    445
Name: fips, dtype: int64

In [8]:
#Sum up the xfact values and muliply by 10 to get actual acres
dfX = grpCounty['xfact'].agg('sum')
dfX = dfX * 10
dfX.head()

fips
37001    27830
37003    16850
37005    15070
37007    34380
37009    27320
Name: xfact, dtype: int64

In [9]:
#Or we can combine the aggregating functions into a single 
# command using a dictionary to define how we want to aggregate

#Create a dictionary of field names: aggregating functions
grpFunctions = {'fips':['count'],'xfact':['sum']}

#Apply them all at once
dfX = grpCounty['xfact'].agg(grpFunctions)
dfX.head()

C:\Users\sb496\AppData\Local\ESRI\conda\envs\my_env\lib\site-packages\ipykernel_launcher.py:8: FutureWarning: using a dict on a Series for aggregation
is deprecated and will be removed in a future version

       fips xfact
      count   sum
fips
37001   369  2783
37003   191  1685
37005   314  1507
37007   336  3438
37009   445  2732

## Transforming data
Pandas can pivot data too. Let's pivot our `dfTrend` table so that it moves the year values into columns and presents the value in the `broad` column (for each year). This is done with the Pandas `pivot` function. The `columns` parameter is where we specify the column on which we want to pivot our data, and the `values` parameter is where we specify the column from which we take the values,

In [10]:
#The table: we want to move the year column to headers and display the broad categories...
dfTrend.head()

,yr,landuse,broad,prime,crp,crpcov,crpnum,dblcrop,irtyp,irsor,...,lenslop,slope,landcl,knoll,wrotat,usle,ei,eiwater,eiwind,aaweq
recordid,,,,,,,,,,,,,,,,,,,,,
37001010001,1982,342,5,1,9,9,99,0,0,0,...,0,0.0,2E,0,0,0.0,0.0,0.0,0.0,0.0
37001010001,1987,342,5,1,9,9,99,0,0,0,...,0,0.0,2E,0,0,0.0,0.0,0.0,0.0,0.0
37001010001,1992,800,8,0,0,0,0,0,0,0,...,0,0.0,NaN,0,0,0.0,0.0,0.0,0.0,0.0
37001010001,1997,800,8,0,0,0,0,0,0,0,...,0,0.0,NaN,0,0,0.0,0.0,0.0,0.0,0.0
37001010002,1982,342,5,0,9,9,99,0,0,0,...,0,0.0,4E,0,0,0.0,0.0,0.0,0.0,0.0

In [11]:
dfX = dfTrend.pivot(columns='yr',values='broad')
dfX.head()

yr          1982 1987 1992 1997
recordid
37001010001    5    5    8    8
37001010002    5    5    5    5
37001010003    5    5    5    5
37001010004    5    5    5    5
37001010005    5    5    5    8

## Joining tables

In [12]:
#Build the broad codes dataFrame
dataDict = {'codes':['1','2','3','4','5','6','7','8','9','10','11','12'],
            'description':['Cropland_cultivated',
                      'Cropland_noncultivated',
                      'Pastureland',
                      'Rangeland',
                      'Forest land',
                      'Other rural land',
                      'Urban and built-up land',
                      'Rural transportation',
                      'Small water areas',
                      'Census water',
                      'Federal land',
                      'Conservation reserve program (CRP) land']}
dfBroadCodes = pd.DataFrame(dataDict,dtype='str')
dfBroadCodes

   codes                              description
0      1                      Cropland_cultivated
1      2                   Cropland_noncultivated
2      3                              Pastureland
3      4                                Rangeland
4      5                              Forest land
5      6                         Other rural land
6      7                  Urban and built-up land
7      8                     Rural transportation
8      9                        Small water areas
9     10                             Census water
10    11                             Federal land
11    12  Conservation reserve program (CRP) land

In [13]:
#Join to the dfX dataFrame
dfY = pd.merge(left=dfTrend,
               right=dfBroadCodes,
               how='outer',
               left_on='broad',
               right_on='codes')

In [14]:
dfY

,yr,landuse,broad,prime,crp,crpcov,crpnum,dblcrop,irtyp,irsor,...,landcl,knoll,wrotat,usle,ei,eiwater,eiwind,aaweq,codes,description
0,1982,342,5,1.0,9.0,9.0,99.0,0.0,0.0,0.0,...,2E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
1,1987,342,5,1.0,9.0,9.0,99.0,0.0,0.0,0.0,...,2E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
2,1982,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
3,1987,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
4,1992,342,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
5,1997,342,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
6,1982,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,6E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
7,1987,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,6E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
8,1992,342,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
9,1997,342,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
10,1982,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
11,1987,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
12,1992,342,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
13,1997,342,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
14,1982,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
15,1987,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
16,1992,342,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
17,1982,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
18,1987,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
19,1992,342,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
20,1982,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
21,1987,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
22,1992,342,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
23,1997,342,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
24,1982,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,6E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
25,1987,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,6E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
26,1992,342,5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,6E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
27,1982,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,6E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
28,1987,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,6E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
29,1982,342,5,0.0,9.0,9.0,99.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.00,0.0,0.0,0.0,0.0,5,Forest land
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
122727,1992,410,12,0.0,1.0,1.0,5.0,0.0,0.0,0.0,...,2E,0.0,0.0,17.83,18.9,18.9,0.0,0.0,12,Conservation reserve program (CRP) land
122728,1997,410,12,0.0,1.0,1.0,5.0,0.0,0.0,0.0,...,2E,0.0,0.0,4.71,18.9,18.9,0.0,0.0,12,Conservation reserve program (CRP) land
122729,1992,410,12,0.0,1.0,1.0,9.0,0.0,0.0,0.0,...,4S,0.0,0.0,0.04,13.3,13.3,0.0,0.0,12,Conservation reserve program (CRP) land
122730,1997,410,12,0.0,1.0,1.0,9.0,0.0,0.0,0.0,...,4S,0.0,0.0,0.04,13.3,13.3,0.0,0.0,12,Conservation reserve program (CRP) land
122731,1992,410,12,0.0,1.0,3.0,10.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.19,47.5,47.5,0.0,0.0,12,Conservation reserve program (CRP) land
122732,1997,410,12,0.0,1.0,3.0,10.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.19,47.5,47.5,0.0,0.0,12,Conservation reserve program (CRP) land
122733,1992,410,12,1.0,1.0,2.0,5.0,0.0,0.0,0.0,...,2E,0.0,0.0,6.59,7.7,7.7,0.0,0.0,12,Conservation reserve program (CRP) land
122734,1997,410,12,1.0,1.0,2.0,5.0,0.0,0.0,0.0,...,2E,0.0,0.0,0.12,8.0,8.0,0.0,0.0,12,Conservation reserve program (CRP) land
122735,1992,410,12,0.0,1.0,2.0,5.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.09,22.5,22.5,0.0,0.0,12,Conservation reserve program (CRP) land
122736,1997,410,12,0.0,1.0,2.0,5.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.09,22.5,22.5,0.0,0.0,12,Conservation reserve program (CRP) land
122737,1992,410,12,0.0,1.0,2.0,5.0,0.0,0.0,0.0,...,4S,0.0,0.0,0.04,8.0,8.0,0.0,0.0,12,Conservation reserve program (CRP) land
122738,1997,410,12,0.0,1.0,2.0,5.0,0.0,0.0,0.0,...,4S,0.0,0.0,0.04,8.0,8.0,0.0,0.0,12,Conservation reserve program (CRP) land
122739,1987,410,12,1.0,9.0,9.0,99.0,0.0,0.0,0.0,...,2E,0.0,0.0,32.30,20.2,20.2,0.0,0.0,12,Conservation reserve program (CRP) land
122740,1992,410,12,1.0,1.0,2.0,2.0,0.0,0.0,0.0,...,2E,0.0,0.0,0.08,20.0,20.0,0.0,0.0,12,Conservation reserve program (CRP) land
122741,1997,410,12,1.0,1.0,2.0,2.0,0.0,0.0,0.0,...,2E,0.0,0.0,0.08,20.0,20.0,0.0,0.0,12,Conservation reserve program (CRP) land
122742,1992,410,12,0.0,1.0,2.0,9.0,0.0,0.0,0.0,...,3W,0.0,0.0,0.02,4.0,4.0,0.0,0.0,12,Conservation reserve program (CRP) land
122743,1997,410,12,0.0,1.0,2.0,9.0,0.0,0.0,0.0,...,3W,0.0,0.0,0.02,4.0,4.0,0.0,0.0,12,Conservation reserve program (CRP) land
122744,1992,410,12,1.0,1.0,2.0,10.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.03,10.0,10.0,0.0,0.0,12,Conservation reserve program (CRP) land
122745,1997,410,12,1.0,1.0,2.0,10.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.03,10.0,10.0,0.0,0.0,12,Conservation reserve program (CRP) land
122746,1992,410,12,1.0,1.0,1.0,10.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.11,9.2,9.2,0.0,0.0,12,Conservation reserve program (CRP) land
122747,1997,410,12,1.0,1.0,1.0,10.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.11,9.2,9.2,0.0,0.0,12,Conservation reserve program (CRP) land
122748,1992,410,12,1.0,1.0,2.0,4.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.03,16.7,16.7,0.0,0.0,12,Conservation reserve program (CRP) land
122749,1992,410,12,0.0,1.0,1.0,7.0,0.0,0.0,0.0,...,4E,0.0,0.0,15.95,14.9,14.9,0.0,0.0,12,Conservation reserve program (CRP) land
122750,1997,410,12,0.0,1.0,1.0,7.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.13,14.4,14.4,0.0,0.0,12,Conservation reserve program (CRP) land
122751,1992,410,12,0.0,1.0,1.0,9.0,0.0,0.0,0.0,...,4E,0.0,0.0,33.67,20.1,20.1,0.0,0.0,12,Conservation reserve program (CRP) land
122752,1997,410,12,0.0,1.0,1.0,9.0,0.0,0.0,0.0,...,4E,0.0,0.0,0.24,20.0,20.0,0.0,0.0,12,Conservation reserve program (CRP) land
122753,1992,410,12,1.0,1.0,1.0,4.0,0.0,0.0,0.0,...,3E,0.0,0.0,0.07,7.8,7.8,0.0,0.0,12,Conservation reserve program (CRP) land
122754,1992,410,12,0.0,1.0,1.0,5.0,0.0,0.0,0.0,...,6E,0.0,0.0,0.54,36.0,36.0,0.0,0.0,12,Conservation reserve program (CRP) land
122755,1997,410,12,0.0,1.0,1.0,5.0,0.0,0.0,0.0,...,6E,0.0,0.0,0.54,36.0,36.0,0.0,0.0,12,Conservation reserve program (CRP) land
122756,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,Rangeland

In [15]:
#Re-pivot
dfTrend.pivot(columns='yr',values='broad')

yr          1982 1987 1992 1997
recordid
37001010001    5    5    8    8
37001010002    5    5    5    5
37001010003    5    5    5    5
37001010004    5    5    5    5
37001010005    5    5    5    8
37001010006    1    1    1    1
37001010007    5    5    5    1
37001010008    6    6    6    6
37001010009    8    8    8    8
37001010010    6    6    6    6
37001010011    5    5    5    5
37001010012    1    1    1    1
37001010013    1    1    1    1
37001010014    5    5    5    7
37001010015    5    5    7    7
37001010016    5    5    5    5
37001010017    5    5    5    5
37001010018    7    7    7    7
37001010019    5    5    5    5
37001010020    5    5    5    5
37001010021    5    5    5    5
37001010022    9    9    9    9
37001010023    8    8    8    8
37001010024    7    7    7    7
37001010025    7    7    7    7
37001010026    7    7    7    7
37001010027    9    9    9    3
37001010028    3    3    7    7
37001010029    3    3    3    7
37001010030    7    7    7    7
...          ...  ...  ...  ...
37994020006    1    1   12   12
37994020007    1    1    1   12
37994020008    1    1   12   12
37994020009    1    1   12    5
37994020010    6    6    6   12
37994020011    1   12   12   12
37994020012    1    1   12   12
37994020013    1    1   12   12
37994020014    1    1   12   12
37994020015    1    2   12   12
37994020016    1   12   12   12
37994020017    1    1   12   12
37994020018    1   12   12   12
37994020019    1   12   12   12
37994020020    1    1   12   12
37994020021    1    1   12   12
37994020022    1    1   12   12
37994020023    1    1   12   12
37994020024    1    1   12   12
37994020025    1    1   12   12
37994020026    1    1   12   12
37994020027    1   12   12   12
37994020028    1    1   12   12
37994020029    1    1   12   12
37994020030    1    1   12   12
37994020031    1    1   12    2
37994020032    1    1   12   12
37994020033    1    1   12   12
37994020034    1    1   12    2
37994020035    1    1   12   12

[30689 rows x 4 columns]